[package]
name = "rusqlite_regex"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "~0.32"
regex = "^1.10"

once_cell = "^1.19"
thiserror = "^1.0"

[build-dependencies]
cbindgen = "~0.27"
cc = "^1.0"
